#lang racket

(require qtops/qualities/area
         qtops/qualities/region
         "../../../../../qualities/brusher.rkt")

(provide <>kingsroad)

(define (<>market t)
  (<>area t #:name "market"))
(define (<>realtor t)
  (<>area t #:name "realtor"))
(define (<>old-bastion t)
  (<>area t #:name "Old Bastion"))
(define (<>mother-joffas t)
  (<>area t #:name "Mother Joffa's Orphanage and Laundromat"))
(define (<>kingsroad-1 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-2 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-3 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-4 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-5 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-6 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-7 t)
  (<>area t #:name "Kingroad"))
(define (<>kingsroad-8 t)
  (<>area t #:name "Kingroad"))

(define (<>kingsroad t)
  (<>Brusher
   (<>region
    t #:name "Kingsroad"
    #:areas `((market ,<>market)
              (realtor ,<>realtor)
              (old-bastion ,<>old-bastion)
              (mother-joffas ,<>mother-joffas)
              (kingsroad-1 ,<>kingsroad-1)
              (kingsroad-2 ,<>kingsroad-2)
              (kingsroad-3 ,<>kingsroad-3)
              (kingsroad-4 ,<>kingsroad-4)
              (kingsroad-5 ,<>kingsroad-5)
              (kingsroad-6 ,<>kingsroad-6)
              (kingsroad-7 ,<>kingsroad-7)
              (kingsroad-8 ,<>kingsroad-8))
    #:links '((kingsroad-1 southeast northwest realtor)
              (kingsroad-2 north south market)
              (kingsroad-4 southwest northeast old-bastion)
              (kingsroad-5 northeast southwest mother-joffas)
              (kingsroad-1 east west kingsroad-2)
              (kingsroad-2 east west kingsroad-3)
              (kingsroad-3 southeast northwest kingsroad-4)
              (kingsroad-4 southeast northwest kingsroad-5)
              (kingsroad-5 east west kingsroad-6)
              (kingsroad-6 east west kingsroad-7)
              (kingsroad-7 east west kingsroad-8)))))
